// Re-export database types for backward compatibility
export type {
  Contact,
  ContactInsert,
  ContactUpdate,
  ContactStatus,
  Deal,
  DealInsert,
  DealUpdate,
  DealStatus,
  Conversation,
  ConversationInsert,
  ConversationUpdate,
  ConversationStatus,
  ChannelType,
  Message,
  MessageInsert,
  Product,
  ProductInsert,
  ProductUpdate,
  ProductClassification,
  BillingInterval,
  KnowledgeSource,
  KnowledgeSourceInsert,
  KnowledgeSourceUpdate,
  KnowledgeType,
  Activity,
  ActivityInsert,
  ActivityType,
  User,
  UserUpdate,
  UserSettings,
  UserSettingsUpdate,
  OutreachPersonality,
  AutomationMode,
  Database
} from '@/lib/database.types'

// Legacy type aliases for backward compatibility with existing components
export type OpportunityFilter = 'all' | 'open' | 'won' | 'lost'
export type DateFilterType = 'day' | 'month' | 'year' | 'custom'

// Campaign configuration (not stored in DB, used for UI)
export interface CampaignConfig {
  channels: string[]
  budget: number
  aggressiveness: number // 1-100
  products: string[]
  objective: string
}

// Insight report (generated by AI, not persisted)
export interface InsightReport {
  summary: string
  forecast: string
  recommendations: string[]
}

// Legacy Message interface for components using old format
export interface LegacyMessage {
  id: string
  sender: 'user' | 'contact' | 'thorne'
  text: string
  timestamp: string
  type?: 'email' | 'sms' | 'call_transcript'
}

// Legacy Contact interface for components using old format
export interface LegacyContact {
  id: string
  firstName: string
  lastName: string
  email: string
  company: string
  status: 'New' | 'Hot' | 'Withering' | 'Dead' | 'Needs Update' | 'Retouch' | 'Recapture'
  addedDate: string
  lastContactDate: string
  address?: string
}

// Legacy Deal interface for components using old format
export interface LegacyDeal {
  id: string
  clientName: string
  amount: number
  status: 'open' | 'closed-won' | 'closed-lost'
  isMonthlyRecurring: boolean
  expectedCloseDate: string
  actualCloseDate?: string
  createdAt: string
}

// Legacy Conversation interface for components using old format
export interface LegacyConversation {
  id: string
  contactId: string
  contactName: string
  lastMessage: string
  lastActive: string
  status: 'awaiting_reply' | 'responded' | 'thorne_handling'
  channel: 'SMS' | 'Email' | 'LinkedIn' | 'WhatsApp'
  unreadCount: number
  messages?: LegacyMessage[]
}

// Legacy Activity interface for components using old format
export interface LegacyActivity {
  id: string
  type: 'Human' | 'Thorne' | 'Gift' | 'System' | 'Update'
  title: string
  detail: string
  date: string
  icon?: string
  oldValue?: string
  newValue?: string
}
